# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Unitcron
tagline:          'Online portfolio'
description:      'Research & projects'
url:              https://unitcron.github.io
baseurl:          /

author:
  name:           'Unitcron'
  url:            https://unitcron.github.io/about

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
